
@startuml UC16_ProcessRandomEvent
title UC-16: Process Random Event

skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 220
skinparam defaultFontSize 12

participant "game:Game" as game
participant "selectedPump:Pump" as selectedPump
participant "targetCistern:Cistern" as targetCistern

game -> game : performRandomEvents()

game -> game : selectRandomWorkingPumps()
game --> game : pumpsToBreak

loop for each selectedPump in pumpsToBreak
    game -> selectedPump : breakElement()
    selectedPump --> game : state=broken
end

game -> game : getCisterns()
game --> game : cisternList

loop for each targetCistern in cisternList
    alt generate pipe
        game -> targetCistern : producePipe()
        targetCistern --> game : newPipe
        game -> game : addElement(newPipe)
    else generate pump
        game -> targetCistern : producePump()
        targetCistern --> game : newPump
        game -> game : addElement(newPump)
    end
end

game -> game : updateGameState()

@enduml
