@startuml UC1_StartNewGame
title UC-1: Start New Game

skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 220
skinparam defaultFontSize 12

actor "Player" as player
participant "game:Game" as game
participant "plumberTeam:Team" as plumberTeam
participant "saboteurTeam:Team" as saboteurTeam
participant "turnManager:TurnManager" as turnManager
participant "turnTimer:Timer" as turnTimer

player -> game : startNewGameCommand()
game -> game : startGame()
game -> game : state=INITIALIZING
game -> game : prepareGameSession()

game -> game : addElement(spring)
game -> game : addElement(cistern)
game -> game : addElement(pump)

game -> game : createTeams(plumberTeam,saboteurTeam)

loop for each participating player
    game -> plumberTeam : addPlayer(player) or
    game -> saboteurTeam : addPlayer(player)
end

game -> plumberTeam : initializeScore(0)
game -> saboteurTeam : initializeScore(0)
game -> game : setGoalScore(targetScore)

game -> turnManager : initialize(turnTimer)
turnManager -> turnManager : selectFirstCurrentPlayer()
turnManager -> turnManager : startTurn()
turnManager -> turnTimer : start()

game -> game : state=RUNNING
game --> player : gameSessionBegins

@enduml